from abc import ABC, abstractmethod

class TokenizerBase(ABC):
    @abstractmethod
    def encode(self, text: str, add_special_tokens: bool = True) -> list[int]: ...
    @abstractmethod
    def decode(self, ids: list[int], skip_special_tokens: bool = True) -> str: ...
    @property
    @abstractmethod
    def vocab_size(self) -> int: ...
    @property
    @abstractmethod
    def bos_token_id(self) -> int: ...
    @property
    @abstractmethod
    def eos_token_id(self) -> int: ...
    @property
    @abstractmethod
    def pad_token_id(self) -> int: ...
    @abstractmethod
    def save(self, directory: str) -> None: ...
    @classmethod
    @abstractmethod
    def load(cls, directory: str) -> 'TokenizerBase': ...
